Repository laferenorg/FGTL2D, pull requests merged in 2021-08, with the labels that each got.

#1 Pull Request | Project Setup
  .gitignore
  AUTHORS
  CMakeLists.txt
  include/FGTL.h
  src/FGTL.c
Labels: Push Back

#2 Pull Request | Litle Changed
  AUTHORS
Labels: Push Back

#4 Pull Request | Idea | Make Pages
  AUTHORS
  README.md
  _config.yml
Labels: Idea, Push Back

#5 Pull Request | Create file management
  CMakeLists.txt
  include/FGTL.h
  include/FGTL_File.h
  src/FGTL_File.cpp
Labels: Push Back

#6 Pull Request | GitHub pages
  README.md
  fgtl/init.md
  fgtl/quit.md
  first_time/first_time.md
Labels: Pull Request

#7 Pull Request | GitHub pages
  fgtl_file/exist_content.md
  fgtl_file/get_list_file.md
  fgtl_file/get_list_file_extension.md
  fgtl_file/get_list_folder.md
  fgtl_file/its_folder.md
  first_time/first_time.md
Labels: Pull Request

#8 Pull Request | Adding Sound Management
  CMakeLists.txt
  include/FGTL.h
  include/FGTL_Sound.h
  src/FGTL.c
  src/FGTL_File.cpp
  src/FGTL_Sound.c
Labels: Pull Request

#9 # Pull Request | Github Pages
  fgtl_sound/execution_music.md
  fgtl_sound/load_sound.md
  fgtl_sound/play_effect.md
  fgtl_sound/play_music.md
  fgtl_sound/set_volume.md
  fgtl_sound/sound.md
  fgtl_sound/sound_free.md
  fgtl_sound/sound_music_choose.md
  first_time/first_time.md
Labels: Pull Request

#10 Pull Request | Add Features
  include/FGTL.h
  include/FGTL_Event.h
  include/FGTL_System.h
  src/FGTL.c
  src/FGTL_Event.c
  src/FGTL_System.c
Labels: Pull Request

#11 Pull Request | Add Features and Fix Bug
  include/FGTL.h
  include/FGTL_Event.h
  include/FGTL_Screen.h
  src/FGTL.c
  src/FGTL_Event.c
  src/FGTL_Screen.cpp
Labels: Pull Request, Idea
